using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using WorldCup2026.Models;

namespace WorldCup2026.Services;

/// <summary>
/// Generates a tournament poster PDF using QuestPDF.
/// </summary>
public class PdfExportService
{
    private const string PrimaryColor = "#1a365d";
    private const string AccentColor = "#c8a951";
    private const string LightBg = "#f7f7f7";

    static PdfExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    /// <summary>
    /// Export a tournament poster PDF with bracket, groups, and stats.
    /// </summary>
    public void ExportPoster(
        string filePath,
        List<Match> bracketMatches,
        List<Group> groups,
        List<PlayerStat> topScorers,
        List<TeamStat> teamStats,
        DateTime lastUpdated)
    {
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A2);
                page.Margin(30);
                page.PageColor(Colors.White);

                // Header
                page.Header().Element(c => ComposeHeader(c, lastUpdated));

                // Content
                page.Content().Element(c => ComposeContent(c, bracketMatches, groups, topScorers, teamStats));

                // Footer
                page.Footer().AlignCenter().Text("Generated by World Cup 2026 App")
                    .FontSize(8).FontColor(Colors.Grey.Medium);
            });
        }).GeneratePdf(filePath);
    }

    private static void ComposeHeader(IContainer container, DateTime lastUpdated)
    {
        container.Column(col =>
        {
            col.Item().AlignCenter().Text("FIFA WORLD CUP 2026™")
                .FontSize(36).Bold().FontColor(PrimaryColor);

            col.Item().AlignCenter().Text("Canada • Mexico • United States")
                .FontSize(16).FontColor(AccentColor);

            col.Item().AlignCenter().Text($"Tournament Poster — Updated: {lastUpdated:yyyy-MM-dd HH:mm}")
                .FontSize(10).FontColor(Colors.Grey.Medium);

            col.Item().PaddingVertical(5).LineHorizontal(1).LineColor(AccentColor);
        });
    }

    private static void ComposeContent(
        IContainer container,
        List<Match> bracketMatches,
        List<Group> groups,
        List<PlayerStat> topScorers,
        List<TeamStat> teamStats)
    {
        container.Column(col =>
        {
            // Section: Knockout Bracket Summary
            col.Item().Element(c => ComposeBracketSection(c, bracketMatches));

            col.Item().PaddingVertical(5).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);

            // Section: Group Standings
            col.Item().Element(c => ComposeGroupSection(c, groups));

            col.Item().PaddingVertical(5).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);

            // Section: Statistics
            col.Item().Element(c => ComposeStatsSection(c, topScorers, teamStats));
        });
    }

    private static void ComposeBracketSection(IContainer container, List<Match> bracketMatches)
    {
        container.Column(col =>
        {
            col.Item().Text("Knockout Stage Bracket").FontSize(18).Bold().FontColor(PrimaryColor);
            col.Item().PaddingVertical(3);

            if (bracketMatches.Count == 0)
            {
                col.Item().Text("Knockout stage has not started yet.").FontSize(12).Italic().FontColor(Colors.Grey.Medium);
                return;
            }

            col.Item().Table(table =>
            {
                table.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(); c.ConstantColumn(60); c.RelativeColumn();
                    c.ConstantColumn(10); c.RelativeColumn(); c.ConstantColumn(60);
                    c.RelativeColumn();
                });

                var stages = new[]
                {
                    (TournamentStage.RoundOf32, "Round of 32"),
                    (TournamentStage.RoundOf16, "Round of 16"),
                    (TournamentStage.QuarterFinal, "Quarter-Finals"),
                    (TournamentStage.SemiFinal, "Semi-Finals"),
                    (TournamentStage.Final, "Final")
                };

                // Header row
                table.Header(header =>
                {
                    foreach (var (_, label) in stages)
                    {
                        header.Cell().Padding(2).Text(label).FontSize(8).Bold()
                            .FontColor(Colors.White).AlignCenter();
                        header.Cell().Padding(2).Background(Colors.White);
                    }
                });

                // Match rows (simplified: show matchups)
                var maxRows = stages.Max(s => bracketMatches.Count(m => m.Stage == s.Item1));
                for (int row = 0; row < maxRows; row++)
                {
                    foreach (var (stage, _) in stages)
                    {
                        var stageMatches = bracketMatches.Where(m => m.Stage == stage).ToList();
                        if (row < stageMatches.Count)
                        {
                            var m = stageMatches[row];
                            table.Cell().Padding(2).Background(row % 2 == 0 ? LightBg : Colors.White)
                                .Text($"{m.HomeTeamCode ?? m.HomeTeamName} vs {m.AwayTeamCode ?? m.AwayTeamName}")
                                .FontSize(7);
                        }
                        else
                        {
                            table.Cell().Padding(2).Text("—").FontSize(7).AlignCenter();
                        }
                        table.Cell().Padding(2); // spacer
                    }
                }
            });
        });
    }

    private static void ComposeGroupSection(IContainer container, List<Group> groups)
    {
        container.Column(col =>
        {
            col.Item().Text("Group Stage Standings").FontSize(18).Bold().FontColor(PrimaryColor);
            col.Item().PaddingVertical(3);

            var orderedGroups = groups.OrderBy(g => g.Name).ToList();
            var midPoint = (orderedGroups.Count + 1) / 2;

            col.Item().Row(row =>
            {
                row.ConstantItem(10);
                row.RelativeItem().Element(c => RenderGroupTable(c, orderedGroups.Take(midPoint).ToList()));
                row.ConstantItem(10);
                row.RelativeItem().Element(c => RenderGroupTable(c, orderedGroups.Skip(midPoint).ToList()));
                row.ConstantItem(10);
            });
        });
    }

    private static void RenderGroupTable(IContainer container, List<Group> groupList)
    {
        container.Column(col =>
        {
            foreach (var group in groupList)
            {
                col.Item().PaddingBottom(8).Column(gcol =>
                {
                    gcol.Item().Background(PrimaryColor).Padding(2)
                        .Text($"Group {group.Name}")
                        .FontSize(11).Bold().FontColor(Colors.White);

                    gcol.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.ConstantColumn(20); c.RelativeColumn();
                            c.ConstantColumn(20); c.ConstantColumn(20);
                            c.ConstantColumn(20); c.ConstantColumn(20);
                            c.ConstantColumn(25);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("#").FontSize(7).Bold();
                            header.Cell().Text("Team").FontSize(7).Bold();
                            header.Cell().Text("P").FontSize(7).Bold().AlignCenter();
                            header.Cell().Text("W").FontSize(7).Bold().AlignCenter();
                            header.Cell().Text("D").FontSize(7).Bold().AlignCenter();
                            header.Cell().Text("L").FontSize(7).Bold().AlignCenter();
                            header.Cell().Text("Pts").FontSize(7).Bold().AlignCenter();
                        });

                        foreach (var s in group.Standings)
                        {
                            table.Cell().Text(s.Position.ToString()).FontSize(7);
                            table.Cell().Text(s.TeamName).FontSize(7);
                            table.Cell().Text(s.Played.ToString()).FontSize(7).AlignCenter();
                            table.Cell().Text(s.Wins.ToString()).FontSize(7).AlignCenter();
                            table.Cell().Text(s.Draws.ToString()).FontSize(7).AlignCenter();
                            table.Cell().Text(s.Losses.ToString()).FontSize(7).AlignCenter();
                            table.Cell().Text(s.Points.ToString()).FontSize(7).Bold().AlignCenter();
                        }
                    });
                });
            }
        });
    }

    private static void ComposeStatsSection(
        IContainer container,
        List<PlayerStat> topScorers,
        List<TeamStat> teamStats)
    {
        container.Row(row =>
        {
            row.RelativeItem().Element(c => ComposeTopScorers(c, topScorers));
            row.ConstantItem(20);
            row.RelativeItem().Element(c => ComposeTeamStats(c, teamStats));
        });
    }

    private static void ComposeTopScorers(IContainer container, List<PlayerStat> topScorers)
    {
        container.Column(col =>
        {
            col.Item().Text("Top Scorers").FontSize(14).Bold().FontColor(PrimaryColor);
            col.Item().PaddingVertical(3);

            col.Item().Table(table =>
            {
                table.ColumnsDefinition(c =>
                {
                    c.ConstantColumn(25); c.RelativeColumn();
                    c.ConstantColumn(45); c.ConstantColumn(35); c.ConstantColumn(35);
                });

                table.Header(header =>
                {
                    header.Cell().Text("#").FontSize(8).Bold();
                    header.Cell().Text("Player").FontSize(8).Bold();
                    header.Cell().Text("Team").FontSize(8).Bold();
                    header.Cell().Text("Goals").FontSize(8).Bold().AlignCenter();
                    header.Cell().Text("Ast").FontSize(8).Bold().AlignCenter();
                });

                foreach (var (s, i) in topScorers.Take(15).Select((s, i) => (s, i)))
                {
                    table.Cell().Text((i + 1).ToString()).FontSize(8);
                    table.Cell().Text(s.PlayerName).FontSize(8);
                    table.Cell().Text(s.TeamCode).FontSize(8);
                    table.Cell().Text(s.Goals.ToString()).FontSize(8).Bold().AlignCenter();
                    table.Cell().Text(s.Assists.ToString()).FontSize(8).AlignCenter();
                }
            });

            col.Item().PaddingTop(8).Text("Golden Boot Race").FontSize(10).Italic().FontColor(Colors.Grey.Medium);
            col.Item().Text("Goals from penalty shootouts are not counted towards individual tallies.").FontSize(7).FontColor(Colors.Grey.Medium);
        });
    }

    private static void ComposeTeamStats(IContainer container, List<TeamStat> teamStats)
    {
        container.Column(col =>
        {
            col.Item().Text("Team Statistics").FontSize(14).Bold().FontColor(PrimaryColor);
            col.Item().PaddingVertical(3);

            col.Item().Table(table =>
            {
                table.ColumnsDefinition(c =>
                {
                    c.ConstantColumn(25); c.RelativeColumn();
                    c.ConstantColumn(35); c.ConstantColumn(35); c.ConstantColumn(35);
                });

                table.Header(header =>
                {
                    header.Cell().Text("#").FontSize(8).Bold();
                    header.Cell().Text("Team").FontSize(8).Bold();
                    header.Cell().Text("GF").FontSize(8).Bold().AlignCenter();
                    header.Cell().Text("GA").FontSize(8).Bold().AlignCenter();
                    header.Cell().Text("GD").FontSize(8).Bold().AlignCenter();
                });

                var sorted = teamStats.OrderByDescending(t => t.GoalsFor).Take(15).ToList();
                foreach (var (t, i) in sorted.Select((t, i) => (t, i)))
                {
                    table.Cell().Text((i + 1).ToString()).FontSize(8);
                    table.Cell().Text(t.TeamName).FontSize(8);
                    table.Cell().Text(t.GoalsFor.ToString()).FontSize(8).AlignCenter();
                    table.Cell().Text(t.GoalsAgainst.ToString()).FontSize(8).AlignCenter();
                    table.Cell().Text(t.GoalDifference.ToString()).FontSize(8).Bold().AlignCenter();
                }
            });
        });
    }
}
